steps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Mirror to Gitee
    uses: Yikun/hub-mirror-action@master
    with:
      src: github/${{ github.repository_owner }}
      dst: gitee/${{ secrets.GITEE_USER }}
      dst_token: ${{ secrets.GITEE_TOKEN }}
      repos: ${{ github.event.repository.name }}
      force_update: true
      debug: true
