name: Sync GitHub To Gitee

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Info
        run: |
          echo "GitHub repo: ${{ github.repository }}"
          echo "Repo owner: ${{ github.repository_owner }}"
          echo "Repo name: ${{ github.event.repository.name }}"

      - name: Mirror to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/${{ github.repository_owner }}
          dst: gitee/${{ secrets.GITEE_USER }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          repos: ${{ github.event.repository.name }}
          force_update: true
          debug: true
